[kijanikiosk_api]
api-staging ansible_host=52.91.31.175

[kijanikiosk_logs]
logs-staging ansible_host=34.229.110.156

[kijanikiosk_payments]
payments-staging ansible_host=3.90.249.226

[kijanikiosk:children]
kijanikiosk_api
kijanikiosk_logs
kijanikiosk_payments

[kijanikiosk:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/kijanikiosk-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
